export const recipes = [
  {
    categoria: "bolo",
    nome: "BOLO DE CHOCOLATE",
    ingredientes: [
      "3 ovos",
      "3/4 xícara de açúcar",
      "2 xícaras de farinha de trigo",
      "3/4 xícara de óleo",
      "1 xícara de água fervendo",
      "1 xícara de nescau",
      "1 colher de sopa de fermento em pó",
    ],
    preparo: [
      "Bata as claras em neve",
      "Em outro recipiente bata as gemas com o açúcar",
      "Adicione o óleo, a farinha de trigo e o nescau",
      "Em seguida adicione a água quente e misture com uma espátula",
      "Por fim, adicione as claras em neve e o fermento",
      "Unte a forma e asse em forno a 160ºC por 40 min",
    ],
    adicionais: [
      {
        titulo: "Cobertura de Brigadeiro",
        ingredientes: [
          "1 lata de leite condensado",
          "1/2 lata de leite",
          "1 colher de margarina",
          "1 e 1/2 colher de chocolate em pó",
        ],
      },
      {
        titulo: "Cobertura de Chocolate",
        ingredientes: [
          "1 xícara de açucar",
          "1 colher de sopa de margarina",
          "3 colheres de sopa de leite",
          "1/2 xícara de nescau",
        ],
      },
    ],
  },
  {
    categoria: "bolo",
    nome: "BROWNIE",
    ingredientes: [
      "200g de chocolate amargo",
      "200g de manteiga",
      "150g de açúcar",
      "100g de chocolate em pó",
      "4 ovos",
      "90g de farinha de trigo",
      "Um punhado de nozes, avelãs, amêndoas, castanhas ou amendoim",
    ],
    preparo: [
      "Derreta o chocolate e a manteiga",
      "Após derreter, adicione o açúcar e misture",
      "Acrescente o chocolate em pó e misture",
      "Acrescente a farinha",
      "Após misturar, coloque as castanhas e misture",
      "Asse por aproximadamente 25 minutos a 180ºC em uma forma com papel manteiga",
    ],
    adicionais: [],
  },
  {
    categoria: "bolo",
    nome: "BOLO CHIFFON",
    ingredientes: [
      "5 ovos grandes ou 6 ovos pequenos",
      "3/4 xícara de açúcar",
      "1 xícara de farinha de trigo",
      "1/4 xícara de óleo",
      "1/2 xícara de leite",
      "1 colher de sopa rasa de fermento em pó",
    ],
    preparo: [
      "Bata as claras em neve, acrescente ½ xícara de açúcar e reserve",
      "Bata as gemas com ½ xícara de açúcar até ficar claro, junte o óleo e continue batendo, acrescente o leite e bata mais um pouco",
      "Acrescente a farinha de trigo, misture levemente com uma espátula, acrescente as claras em neve e o fermento em pó",
      "Coloque a massa na forma (sem untar) e leve ao forno médio (160ºC) para assar por 35~40 minutos",
      "Após retirar do forno, deixe de ponta cabeça até esfriar",
      "Para retirar da forma passe uma faca ao redor",
    ],
    adicionais: [],
  },
  {
    categoria: "bolo",
    nome: "BOLO CHIFFON DE MATCHÁ",
    ingredientes: [
      "5 ovos grandes ou 6 ovos pequenos",
      "3/4 xícara de açúcar",
      "1 xícara de farinha de trigo",
      "1/4 xícara de óleo",
      "1/2 xícara de leite",
      "1 colher de sopa rasa de fermento em pó",
      "15g de matchá",
    ],
    preparo: [
      "Bata as claras em neve, acrescente ½ xícara de açúcar e reserve",
      "Bata as gemas com ½ xícara de açúcar até ficar claro, junte o óleo e continue batendo, acrescente o leite e bata mais um pouco",
      "Acrescente a farinha de trigo com o matchá, misture levemente com uma espátula, acrescente as claras em neve e o fermento em pó",
      "Coloque a massa na forma (sem untar) e leve ao forno médio (160ºC) para assar por 35~40 minutos",
      "Após retirar do forno, deixe de ponta cabeça até esfriar",
      "Para retirar da forma passe uma faca ao redor",
    ],
    adicionais: [],
  },
  {
    categoria: "bolo",
    nome: "BOLO GELADO",
    ingredientes: [
      "4 ovos",
      "2 xícaras de açúcar",
      "2 xícaras de farinha de trigo",
      "1 xícara de leite",
      "1 colher de sopa de fermento em pó",
      "2 xícaras de água",
      "½ lata de leite condensado",
      "5 colheres de sopa de açúcar",
      "1 pacote de coco ralado",
    ],
    preparo: [
      "Para o bolo:Bata as claras em neve",
      "Bata as gemas com o açúcar até obter um creme, acrescente a farinha e o leite, aos poucos e sempre batendo ",
      "Acrescente o fermento e as claras em neve, misturando com uma espátula delicadamente",
      "Despeje em uma forma untada e enfarinhada de 20x30",
      "Leve ao forno pré-aquecido em temperatura moderada (160ºC)",
      "Depois de morno desenforme, corte em quadrados, umedeça com a calda, passe no coco ralado e embrulhe no papel alumínio, deixando na geladeira",
      "Para a calda: Leve ao fogo todos os ingredientes com exceção do coco ralado",
      "Tire do fogo quando obtiver uma calda rala",
      "Deixe esfriar e passe no bolo",
    ],
    adicionais: [],
  },
  {
    categoria: "bolo",
    nome: "MUFFIN",
    ingredientes: [
      "2 xícaras de farinha",
      "½ xícara de açúcar cristal",
      "1 colher de sopa de fermento",
      "½ colher de chá de sal",
      "1 xícara de leite desnatado",
      "1 colher de chá de essência de baunilha",
      "1 ovo grande",
      "¼ xícara de óleo vegetal ou de canola",
    ],
    preparo: [
      "Pré-aqueça o forno a 200ºC e unte as formas de cupcake",
      "Misture a farinha, o fermento e o sal",
      "Em outro recipiente misture o açúcar, o leite, a essência de baunilha, o ovo e o óleo",
      "Junte todos os ingredientes e misture (não muito e a massa não precisa estar lisa)",
      "Coloque em ¾ das forminhas",
      "Coloque os recheios/coberturas, gotas de chocolate, aveia com açúcar mascavo, frutas e etc",
      "Asse por 20 minutos",
    ],
    adicionais: [],
  },
  {
    categoria: "docinhos",
    nome: "BRIGADEIRO",
    ingredientes: [
      "2 latas de leite condensado",
      "1 lata de leite",
      "4 colheres de sopa de chocolate em pó (ou mais a gosto)",
      "2 colheres de sopa de manteiga",
      "Granulado caso seja para enrolar",
    ],
    preparo: ["Cozinhe todos os ingredientes", "Espere esfriar para enrolar"],
    adicionais: [],
  },
  {
    categoria: "docinhos",
    nome: "COOKIES",
    ingredientes: [
      "120g de açúcar cristal",
      "150g de açúcar mascavo",
      "3g de bicarbonato de sódio",
      "150g de chocolate em gotas",
      "1 colher de chá de essência de baunilha",
      "350g de farinha de trigo",
      "200g de manteiga sem sal em temperatura ambiente",
      "1 ovo",
      "2g de sal",
    ],
    preparo: [
      "Pré-aqueça o forno a 180ºC",
      "Peneire em um pote a farinha de trigo, o bicarbonato de sódio e o sal, misture e reserve",
      "Bata em um bowl grande, com um fouet, o ovo, a manteiga amolecida, o açúcar cristal, o açúcar mascavo peneirado e a essência de baunilha",
      "Adicione aos poucos a mistura da farinha e vá misturando com uma espátula",
      "Com a massa pronta acrescente as gotas de chocolate",
      "Forre a assadeira com papel manteiga e asse os cookies por aproximadamente 10 minutos",
      "Tire os cookies da forma após esfriarem",
    ],
    adicionais: [],
  },
  {
    categoria: "docinhos",
    nome: "CHOUX CREAM",
    ingredientes: [
      "80g de margarina",
      "1 xícara de água fervente",
      "3 ovos inteiros",
      "1 xícara de farinha de trigo",
      "Uma pitada de sal",
      "Açúcar de confeiteiro",
    ],
    preparo: [
      "Coloque a água quente, o sal e a margarina numa panela e leve ao fogo",
      "Acrescente a farinha, misture até desgrudar do fundo da panela e tire do fogo",
      "Coloque os ovos",
      "Faça as bolinhas com a massa e leve ao forno por aproximadamente 35 minutos a 180ºC",
    ],
    adicionais: [],
  },
  {
    categoria: "docinhos",
    nome: "CHEESECAKE",
    ingredientes: [
      "1 ½ pacote de bolacha maizena",
      "150g de manteiga derretida",
      "1 leite condensado",
      "1 caixa de creme de leite",
      "300g de cream cheese",
      "1 pacote de gelatina em pó incolor e sem sabor",
    ],
    preparo: [
      "Para a massa: Misture a bolacha triturada com a manteiga e forre a forma de fundo removível",
      "Asse por 5 a 8 minutos a 180ºC",
      "Para o recheio: Bata o leite condensado, o creme de leite e o cream cheese até ficar homogêneo",
      "Acrescente a gelatina dissolvida conforme a embalagem e bata até misturar tudo",
      "Coloque em cima da massa e depois deixe por pelo menos 3 horas na geladeira",
      "Cheesecake de Limão: Use o suco de 2 limões e não coloque a gelatina",
      "Cheesecake de Doce de Leite: Coloque o doce de leite junto com o leite condensado a gostoa",
      "Cheesecake com Calda: Usar geleia pronta ou dissolver goiabada com água no fogo",
    ],
    adicionais: [],
  },
  {
    categoria: "docinhos",
    nome: "CHEESECAKE AMERICANO",
    ingredientes: [
      "200g de bolacha maizena",
      "70g de manteiga",
      "900g de cream cheese em temperatura ambiente (6 pacotes)",
      "5 claras",
      "5 gemas",
      "1 xícara de açúcar",
      "1 colher de sopa de farinha",
      "1 colher de sopa de maizena",
      "400g de sour cream (creme de leite fresco + ½ limão)",
      "1 colher de sopa de essência de baunilha",
      "2 caixas de morango",
      "3 colheres de sopa de açúcar",
      "½ limão",
    ],
    preparo: [
      "Para a massa: Triture a bolacha maizena",
      "Acrescente a manteiga",
      "Forre o fundo da forma com a massa",
      "Leve ao forno pré-aquecido por 8 minutos e deixe esfriar",
      "Para o recheio: Misture o cream cheese com as gemas",
      "Adicione a maizena, a farinha, o açúcar, a baunilha e o sour cream e bata",
      "Bata as claras em neve",
      "Misture as claras em neve com o resto do recheio",
      "Forre por fora a forma com papel alumínio para por em banho maria",
      "Deixe assando por 1 hora e mais 1 hora descansando no forno",
      "Deixe na geladeira",
      "Para a Calda: Coloque em uma panela os morangos, o açúcar e o limão",
      "Deixe cozinhar",
      "Quando esfriar coloque sobre o cheesecake",
    ],
    adicionais: [],
  },
  {
    categoria: "docinhos",
    nome: "PUDIM",
    ingredientes: [
      "1 lata de leite condensado",
      "1 ½ lata de leite",
      "4 ovos",
      "Açúcar para o caramelo",
    ],
    preparo: [
      "Bata as claras em neve, misture as gemas, o leite condensado e o leite",
      "Despeje em forma forrada com açúcar queimado",
      "Cozinhe por 45 minutos em banho maria",
      "Depois que esfriar pode desenformar",
    ],
    adicionais: [],
  },
  {
    categoria: "docinhos",
    nome: "TORTA DE CHOCOLATE",
    ingredientes: [
      "300g de farinha de trigo",
      "150g de manteiga sem sal",
      "1 ovo",
      "Uma pitada de sal",
      "45g de açúcar",
      "280ml de creme de leite",
      "200g de chocolate 40% ou 70% amargo",
    ],
    preparo: [
      "Para a massa: Misture a farinha e a manteiga até formar uma farofa",
      "Acrescente o ovo e misture",
      "Acrescente o açúcar e misture até dar o ponto, se achar que está duro acrescente água gelada",
      "Enrole em insulfilme e deixe na geladeira por pelo menos 1 hora",
      "Asse a massa por 20 minutos a 200ºC",
      "Para o recheio: Esquente o creme de leite coloque o chocolate e misture",
      "Coloque em cima da massa",
    ],
    adicionais: [],
  },
  {
    categoria: "outros",
    nome: "RECHEIO DE CREME",
    ingredientes: [
      "1 lata de leite condensado",
      "2 latas de leite",
      "2 colheres de sopa de maizena",
      "2 gemas",
    ],
    preparo: [
      "Misture todos os ingredientes na panela e levar ao fogo até reduzir e virar um creme",
    ],
    adicionais: [],
  },
  {
    categoria: "lanche",
    nome: "PANQUECA AMERICANA",
    ingredientes: [
      "1 xícara de farinha de trigo ",
      "1 xícara de iogurte natural ",
      "2 colheres de sopa de açúcar ",
      "1 ½ colher de sopa de fermento ",
      "Uma pitada de sal ",
      "1 colher de sopa de manteiga ",
      "2 ovos ",
    ],
    preparo: [
      "Bata todos os ingredientes no liquidificador, deixando a farinha e o fermento por último ",
      "Unte uma frigideira antiaderente e coloque a massa ",
      "Quando dourar de um lado, vire com cuidado e espere o outro lado dourar ",
      " Pode colocar gotas de chocolate, amoras, blueberries e etc e servir com mel, manteiga, calda de chocolate e etc",
    ],
    adicionais: [],
  },
  {
    categoria: "lanche ",
    nome: "PANQUECA PROTEICA",
    ingredientes: [
      "¼ copo de aveia ",
      "1 scoop de whey ",
      "½ banana ",
      "2 colheres de sopa de leite ",
      "1 ovo ",
      "1 colher de chá de fermento ",
      "1 colher de chá de canela ",
      "1 colher de sopa de eritritol",
    ],
    preparo: [
      "Bata todos os ingredientes no liquidificador ",
      "Unte e aqueça uma frigideira com antiaderente ",
      "Faça as panquecas ",
    ],
    adicionais: [],
  },
];
